var courses=
[{"title":"Learn IOS development, Website design, Freelancing",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":159,"author":"Jack smith","img":"https://img-a.udemycdn.com/course/240x135/613808_3c1c_6.jpg"}
,{"title":"Leadership: Practical Leadership Skills",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":40,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/637930_9a22_19.jpg"
},
{"title":"An Entire MBA in 1 Course:Award Winning Business School Prof",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":150,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/762616_7693_3.jpg"},
{"title":"PMP Exam Prep Seminar - PMBOK Guide 6",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":100,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/1361790_2eb7.jpg"},
{"title":"Java Tutorial for Complete Beginners",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":300,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/24823_963e_14.jpg"},
{"title":"Advanced CSS and Sass: Flexbox, Grid, Animations and More!",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":134,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/1026604_790b_2.jpg"},
{"title":"Cisco CCNA 200-301 – The Complete Guide to Getting Certified",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":166,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/1203374_6d6f_3.jpg"},
{"title":"2020 Complete Python Bootcamp: From Zero to Hero in Python",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":230,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/567828_67d0.jpg"},
{"title":"Automate the Boring Stuff with Python Programming",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":136,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/543600_64d1_4.jpg"},
{"title":"The Web Developer Bootcamp",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":169,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg"},
{"title":"React - The Complete Guide (incl Hooks, React Router, Redux)",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":134,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/1362070_b9a1_2.jpg"},
{"title":"The Data Science Course 2020: Complete Data Science Bootcamp",
"description":"Lorem ipsum dolor sit amet, Of the consectetur adipiscing",
"price":234,"author":"Jack smith",
"img":"https://img-a.udemycdn.com/course/240x135/1754098_e0df_3.jpg"}

];

export default courses;